version = 0.1

[default.deploy.parameters]
stack_name = "erglytics-dev"
resolve_s3 = true
s3_prefix = "erglytics-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "CognitoDomainPrefix=\"rowlytics-auth\" AppBaseUrl=\"https://v353vlxck0.execute-api.us-east-2.amazonaws.com/Prod\" SesFromEmail=\"erglytics@gmail.com\""

[default.global.parameters]
region = "us-east-2"
