version = 0.1

[default.deploy.parameters]
stack_name = "erglytics-dev"
resolve_s3 = true
s3_prefix = "erglytics-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoDomainPrefix=\"rowlytics-auth\""
image_repositories = []
disable_rollback = true

[default.global.parameters]
region = "us-east-2"
